In [1]:
import chemistry as chem
import autohf as hf
import time
from tqdm import tqdm
import autograd
import numpy as np
import openfermion
import autograd.numpy as anp
from pennylane import qchem
import pennylane as qml
import autograd.scipy as sc
from autograd.extend import primitive, defvjp

In [2]:
r = anp.array([0.0, 0.0, -0.694347576012433, 0.0, 0.0, 0.694347576012433])
R1, R2 = anp.array(r[0:3]), anp.array(r[3:6])

In [3]:
# Initializes the atomic basis set for Hartree-Fock

M1, M2 = hf.basis_set_params('sto-3g', ['H', 'H']) # Generates default information for hydrogen

basis_set = []

# Generates atomic orbitals using the default information
for func in M1 + M2:
    L, exp, coeff = func
    basis_set.append(hf.AtomicBasisFunction(L, C=anp.array(coeff), A=anp.array(exp)))

In [5]:
num_elecs = 2

# Generates one and two electron integrals
start = time.time()
one_elec, two_elec = hf.electron_integrals(num_elecs, basis_set)([r[0:3]], [r[3:6]])
print("Execution Time = {} s".format(time.time() - start))
print("----------------------------")
print("One Electron Integrals")
print(one_elec)
print("----------------------------")
print("Two Electron Integrals")
print(two_elec)

[[[[0.77460594 0.44752243]
   [0.44752243 0.57192752]]

  [[0.44752243 0.30100731]
   [0.30100731 0.44752243]]]


 [[[0.44752243 0.30100731]
   [0.30100731 0.44752243]]

  [[0.57192752 0.44752243]
   [0.44752243 0.77460594]]]]
Execution Time = 0.029052019119262695 s
----------------------------
One Electron Integrals
[[-1.25642052  0.        ]
 [ 0.         -0.47181021]]
----------------------------
Two Electron Integrals
[[[[ 6.75735764e-01  0.00000000e+00]
   [ 0.00000000e+00  1.80923717e-01]]

  [[ 0.00000000e+00  1.80923717e-01]
   [ 6.64605114e-01  1.11022302e-16]]]


 [[[ 0.00000000e+00  6.64605114e-01]
   [ 1.80923717e-01 -1.11022302e-16]]

  [[ 1.80923717e-01  0.00000000e+00]
   [-1.11022302e-16  6.98598504e-01]]]]
