In [2]:
import numpy as np
from data import Molecule, energy
from hartreefock import hartree_fock

In [3]:
R = [[0.0, 0.0, -0.694347576012433],
     [0.0, 0.0, 0.694347576012433]]

symbols = ['H', 'H']

params = ['r'] # differentiable parameters, 'r' indicates Gaussian centers

In [4]:
mol = Molecule(symbols, R, params = params)

In [6]:
R1, R2 = [np.array([0.0, 0.0, -0.694347576012433]),
          np.array([0.0, 0.0, 0.694347576012433])]

hf_data = hartree_fock(mol.n_electrons, mol.basis_set)([R1], [R2]) # hartree_fock can be modified to take the Molecule object as input

In [7]:
hf_data

(array([-0.58068475,  0.6764763 ]),
 array([[-0.54828754, -1.2184862 ],
        [-0.54828754,  1.2184862 ]]),
 array([[-0.36899994, -0.59681444],
        [-0.59681444, -0.36899994]]),
 array([[-1.12430532, -0.96541548],
        [-0.96541548, -1.12430532]]),
 array([[[[0.77460594, 0.44752243],
          [0.44752243, 0.57192752]],
 
         [[0.44752243, 0.30100731],
          [0.30100731, 0.44752243]]],
 
 
        [[[0.44752243, 0.30100731],
          [0.30100731, 0.44752243]],
 
         [[0.57192752, 0.44752243],
          [0.44752243, 0.77460594]]]]))

In [8]:
e = energy(mol.n_electrons, mol.nuclear_charges, [R1, R2], hf_data) # the energy function needs some work

In [9]:
print(e)

-1.117004820624118
